In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_data_1000_rows.csv") # While using Jupiter Notebook use 'r' before the double colon.
df.head()

,sr_no,name,study_hr_per_week,sub1_marks,sub2_marks,sub3_marks,sub4_marks,sub5_marks,average_marks,sgpa,grade
0,1,Student_0001,16,59,61,36,86,39,56.2,5.62,B
1,2,Student_0002,29,48,84,66,94,47,67.8,6.78,B+
2,3,Student_0003,9,49,38,82,43,87,59.8,5.98,B
3,4,Student_0004,18,85,73,92,70,59,75.8,7.58,A
4,5,Student_0005,24,87,62,35,73,70,65.4,6.54,B+

In [5]:
print("Dataset Shape: ", df.shape)
print("\nDataset Info: \n")
df.info()

Dataset Shape:  (1000, 11)

Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sr_no              1000 non-null   int64
 1   name               1000 non-null   object
 2   study_hr_per_week  1000 non-null   int64
 3   sub1_marks         1000 non-null   int64
 4   sub2_marks         1000 non-null   int64
 5   sub3_marks         1000 non-null   int64
 6   sub4_marks         1000 non-null   int64
 7   sub5_marks         1000 non-null   int64
 8   average_marks      1000 non-null   float64
 9   sgpa               1000 non-null   float64
 10  grade              1000 non-null   object
dtypes: float64(2), int64(7), object(2)
memory usage: 86.1+ KB

In [6]:
def classify_data_type(series):
    if series.dtype == 'object':
        return "Qualitative"
    elif np.issubdtype(series.dtype, np.integer):
        return "Quantitative - Discrete"
    elif np.issubdtype(series.dtype, np.floating):
        return "Quantitative - Continuous"
    else:
        return "Unknown"

In [7]:
def Identify_scale(column):
    col = column.lower()

    if col in ["name","marks"]:
        if col == "marks":
            return "Ordinal"
        return "Nominal"

    if col in ["sub1", "sub2", "sub3", "sub4","sub5"]:
        return "Interval"


    if col in ["study_hr_per_week", "sgpa","sr_no"]:
        return "Ratio"

    return "Ratio (Assumed)"

In [9]:
results = []

for col in df.columns:
    data_type = classify_data_type(df[col])
    scale = Identify_scale(col)
    results.append([col,data_type,scale])


classification_df = pd.DataFrame(results,columns=["attribute","Data Types","Scale of Measurment"])
classification_df

            attribute                 Data Types Scale of Measurment
0               sr_no    Quantitative - Discrete               Ratio
1                name                Qualitative             Nominal
2   study_hr_per_week    Quantitative - Discrete               Ratio
3          sub1_marks    Quantitative - Discrete     Ratio (Assumed)
4          sub2_marks    Quantitative - Discrete     Ratio (Assumed)
5          sub3_marks    Quantitative - Discrete     Ratio (Assumed)
6          sub4_marks    Quantitative - Discrete     Ratio (Assumed)
7          sub5_marks    Quantitative - Discrete     Ratio (Assumed)
8       average_marks  Quantitative - Continuous     Ratio (Assumed)
9                sgpa  Quantitative - Continuous               Ratio
10              grade                Qualitative     Ratio (Assumed)